version: '3'
env:
  GOPATH:
    sh: pwd

vars:
  TARCMD: xzvf

tasks:

  default: 
    - task: task
    - task: wsk
    - task: kind
    - task: kubectl

  clean: rm -v ../bin/*.ver

  download:
    cmds:
    - curl -sL {{.URL}} >{{.CMD}}
    - chmod +x {{.CMD}}
    - echo "{{.URL}}" >{{.CMD}}.ver
    status:
      - fgrep {{.URL}} {{.CMD}}.ver
    dir: ../bin

  task:
    - task: download-tgz
      vars:
        URL: "https://github.com/go-task/task/releases/download/v3.19.1/task_{{OS}}_{{ARCH}}.tar.gz"
        CMD: "task"

  wsk:
    - task: download
      vars: 
        URL: "https://github.com/nuvolaris/openwhisk-cli/releases/download/v0.3.0-morpheus.23011510/wsk-v0.3.0-morpheus.23011510-{{OS}}-{{ARCH}}"
        CMD: "wsk"

  kubectl:
    - task: download
      vars:
        URL: https://dl.k8s.io/release/v1.26.0/bin/{{OS}}/{{ARCH}}/kubectl
        CMD: kubectl

  kind:
    - task: download
      vars:
        URL: https://kind.sigs.k8s.io/dl/v0.17.0/kind-{{OS}}-{{ARCH}}
        CMD: kind    
      